version: '3.2'

services:
  somescylla:
    image: scylladb/scylla:4.3.1
    container_name: somescylla
    volumes:
      - ./:/project
    ports:
      - 9042:9042
      - 9160:9160

  somescylla2:
    image: scylladb/scylla:4.3.1
    container_name: somescylla2
    command: --seeds=somescylla

  somescylla3:
    image: scylladb/scylla:4.3.1
    container_name: somescylla3
    command: --seeds=somescylla