name: ScyllaDB-tests

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          path: ./server
      - name: Start docker compose
        run: |
          cd ./server
          docker-compose up -d
          cargo run